import type { BudgetYearData, BudgetTrend } from './types';

export const BUDGET_COLORS: Record<string, string> = {
  'social': '#3b82f6',
  'education': '#10b981',
  'health': '#f59e0b',
  'general': '#8b5cf6',
  'security': '#ef4444',
  'economy': '#6366f1',
  'defense': '#ec4899',
  'environment': '#14b8a6',
  'housing': '#06b6d4',
  'culture': '#f97316',
  'tech': '#a855f7',
  'debt': '#64748b',
};

export const BUDGET_DATA: Record<number, BudgetYearData> = {
  2024: {
    year: 2024,
    totalApproved: 100_000,
    totalRevised: 101_200,
    totalActual: 94_200,
    executionRate: 93.1,
    sectors: [
      {
        id: 'social',
        name: 'Protecție Socială',
        nameRu: 'Социальная защита',
        nameEn: 'Social Protection',
        code: '10',
        approved: 28_500,
        revised: 29_100,
        actual: 27_200,
        color: BUDGET_COLORS.social,
      },
      {
        id: 'education',
        name: 'Educație',
        nameRu: 'Образование',
        nameEn: 'Education',
        code: '09',
        approved: 18_200,
        revised: 18_400,
        actual: 17_100,
        color: BUDGET_COLORS.education,
      },
      {
        id: 'health',
        name: 'Sănătate',
        nameRu: 'Здравоохранение',
        nameEn: 'Healthcare',
        code: '07',
        approved: 15_800,
        revised: 16_100,
        actual: 14_900,
        color: BUDGET_COLORS.health,
      },
      {
        id: 'general',
        name: 'Servicii Generale de Stat',
        nameRu: 'Общегосударственные услуги',
        nameEn: 'General Public Services',
        code: '01',
        approved: 9_400,
        revised: 9_600,
        actual: 8_800,
        color: BUDGET_COLORS.general,
      },
      {
        id: 'security',
        name: 'Ordine Publică și Securitate',
        nameRu: 'Общественный порядок и безопасность',
        nameEn: 'Public Order & Security',
        code: '03',
        approved: 8_600,
        revised: 8_700,
        actual: 8_100,
        color: BUDGET_COLORS.security,
      },
      {
        id: 'economy',
        name: 'Afaceri Economice',
        nameRu: 'Экономические вопросы',
        nameEn: 'Economic Affairs',
        code: '04',
        approved: 7_200,
        revised: 7_400,
        actual: 6_900,
        color: BUDGET_COLORS.economy,
      },
      {
        id: 'defense',
        name: 'Apărare Națională',
        nameRu: 'Национальная оборона',
        nameEn: 'National Defense',
        code: '02',
        approved: 4_100,
        revised: 4_200,
        actual: 3_900,
        color: BUDGET_COLORS.defense,
      },
      {
        id: 'environment',
        name: 'Mediu și Resurse Naturale',
        nameRu: 'Охрана окружающей среды',
        nameEn: 'Environment',
        code: '05',
        approved: 2_800,
        revised: 2_800,
        actual: 2_600,
        color: BUDGET_COLORS.environment,
      },
      {
        id: 'housing',
        name: 'Locuințe și Servicii Comunale',
        nameRu: 'Жилищно-коммунальные услуги',
        nameEn: 'Housing & Community',
        code: '06',
        approved: 1_900,
        revised: 1_900,
        actual: 1_700,
        color: BUDGET_COLORS.housing,
      },
      {
        id: 'culture',
        name: 'Cultură, Sport și Recreere',
        nameRu: 'Культура, спорт и отдых',
        nameEn: 'Culture, Sport & Recreation',
        code: '08',
        approved: 1_500,
        revised: 1_500,
        actual: 1_400,
        color: BUDGET_COLORS.culture,
      },
      {
        id: 'debt',
        name: 'Datorie Publică',
        nameRu: 'Государственный долг',
        nameEn: 'Public Debt Service',
        code: '12',
        approved: 2_000,
        revised: 2_000,
        actual: 1_600,
        color: BUDGET_COLORS.debt,
      },
    ],
  },
  2023: {
    year: 2023,
    totalApproved: 93_100,
    totalRevised: 94_500,
    totalActual: 88_500,
    executionRate: 93.6,
    sectors: [
      { id: 'social', name: 'Protecție Socială', nameRu: 'Социальная защита', nameEn: 'Social Protection', code: '10', approved: 26_400, revised: 27_000, actual: 25_200, color: BUDGET_COLORS.social },
      { id: 'education', name: 'Educație', nameRu: 'Образование', nameEn: 'Education', code: '09', approved: 16_900, revised: 17_100, actual: 16_000, color: BUDGET_COLORS.education },
      { id: 'health', name: 'Sănătate', nameRu: 'Здравоохранение', nameEn: 'Healthcare', code: '07', approved: 14_600, revised: 14_800, actual: 13_800, color: BUDGET_COLORS.health },
      { id: 'general', name: 'Servicii Generale de Stat', nameRu: 'Общегосударственные услуги', nameEn: 'General Public Services', code: '01', approved: 8_700, revised: 8_900, actual: 8_200, color: BUDGET_COLORS.general },
      { id: 'security', name: 'Ordine Publică și Securitate', nameRu: 'Общественный порядок', nameEn: 'Public Order & Security', code: '03', approved: 7_900, revised: 8_000, actual: 7_500, color: BUDGET_COLORS.security },
      { id: 'economy', name: 'Afaceri Economice', nameRu: 'Экономические вопросы', nameEn: 'Economic Affairs', code: '04', approved: 6_800, revised: 7_000, actual: 6_300, color: BUDGET_COLORS.economy },
      { id: 'defense', name: 'Apărare Națională', nameRu: 'Национальная оборона', nameEn: 'National Defense', code: '02', approved: 3_600, revised: 3_700, actual: 3_400, color: BUDGET_COLORS.defense },
      { id: 'environment', name: 'Mediu și Resurse Naturale', nameRu: 'Охрана окружающей среды', nameEn: 'Environment', code: '05', approved: 2_600, revised: 2_600, actual: 2_400, color: BUDGET_COLORS.environment },
      { id: 'housing', name: 'Locuințe și Servicii Comunale', nameRu: 'Жилищно-коммунальные услуги', nameEn: 'Housing & Community', code: '06', approved: 1_700, revised: 1_700, actual: 1_500, color: BUDGET_COLORS.housing },
      { id: 'culture', name: 'Cultură, Sport și Recreere', nameRu: 'Культура, спорт и отдых', nameEn: 'Culture & Sport', code: '08', approved: 1_400, revised: 1_400, actual: 1_300, color: BUDGET_COLORS.culture },
      { id: 'debt', name: 'Datorie Publică', nameRu: 'Государственный долг', nameEn: 'Public Debt', code: '12', approved: 2_500, revised: 2_300, actual: 2_900, color: BUDGET_COLORS.debt },
    ],
  },
  2022: {
    year: 2022,
    totalApproved: 84_200,
    totalRevised: 85_000,
    totalActual: 79_800,
    executionRate: 93.9,
    sectors: [
      { id: 'social', name: 'Protecție Socială', nameRu: 'Социальная защита', nameEn: 'Social Protection', code: '10', approved: 23_800, revised: 24_100, actual: 22_600, color: BUDGET_COLORS.social },
      { id: 'education', name: 'Educație', nameRu: 'Образование', nameEn: 'Education', code: '09', approved: 15_200, revised: 15_400, actual: 14_400, color: BUDGET_COLORS.education },
      { id: 'health', name: 'Sănătate', nameRu: 'Здравоохранение', nameEn: 'Healthcare', code: '07', approved: 13_100, revised: 13_300, actual: 12_400, color: BUDGET_COLORS.health },
      { id: 'general', name: 'Servicii Generale de Stat', nameRu: 'Общегосударственные услуги', nameEn: 'General Public Services', code: '01', approved: 7_900, revised: 8_000, actual: 7_500, color: BUDGET_COLORS.general },
      { id: 'security', name: 'Ordine Publică și Securitate', nameRu: 'Общественный порядок', nameEn: 'Public Order & Security', code: '03', approved: 7_100, revised: 7_200, actual: 6_700, color: BUDGET_COLORS.security },
      { id: 'economy', name: 'Afaceri Economice', nameRu: 'Экономические вопросы', nameEn: 'Economic Affairs', code: '04', approved: 6_200, revised: 6_400, actual: 5_800, color: BUDGET_COLORS.economy },
      { id: 'defense', name: 'Apărare Națională', nameRu: 'Национальная оборона', nameEn: 'National Defense', code: '02', approved: 3_100, revised: 3_200, actual: 2_900, color: BUDGET_COLORS.defense },
      { id: 'environment', name: 'Mediu și Resurse Naturale', nameRu: 'Охрана окружающей среды', nameEn: 'Environment', code: '05', approved: 2_400, revised: 2_400, actual: 2_200, color: BUDGET_COLORS.environment },
      { id: 'housing', name: 'Locuințe și Servicii Comunale', nameRu: 'Жилищно-коммунальные услуги', nameEn: 'Housing & Community', code: '06', approved: 1_500, revised: 1_500, actual: 1_400, color: BUDGET_COLORS.housing },
      { id: 'culture', name: 'Cultură, Sport și Recreere', nameRu: 'Культура, спорт и отдых', nameEn: 'Culture & Sport', code: '08', approved: 1_200, revised: 1_200, actual: 1_100, color: BUDGET_COLORS.culture },
      { id: 'debt', name: 'Datorie Publică', nameRu: 'Государственный долг', nameEn: 'Public Debt', code: '12', approved: 2_700, revised: 2_300, actual: 2_800, color: BUDGET_COLORS.debt },
    ],
  },
  2021: {
    year: 2021,
    totalApproved: 75_400,
    totalRevised: 76_200,
    totalActual: 72_400,
    executionRate: 95.0,
    sectors: [
      { id: 'social', name: 'Protecție Socială', nameRu: 'Социальная защита', nameEn: 'Social Protection', code: '10', approved: 21_200, revised: 21_500, actual: 20_300, color: BUDGET_COLORS.social },
      { id: 'education', name: 'Educație', nameRu: 'Образование', nameEn: 'Education', code: '09', approved: 13_600, revised: 13_800, actual: 13_000, color: BUDGET_COLORS.education },
      { id: 'health', name: 'Sănătate', nameRu: 'Здравоохранение', nameEn: 'Healthcare', code: '07', approved: 11_800, revised: 12_000, actual: 11_300, color: BUDGET_COLORS.health },
      { id: 'general', name: 'Servicii Generale de Stat', nameRu: 'Общегосударственные услуги', nameEn: 'General Public Services', code: '01', approved: 7_100, revised: 7_200, actual: 6_800, color: BUDGET_COLORS.general },
      { id: 'security', name: 'Ordine Publică și Securitate', nameRu: 'Общественный порядок', nameEn: 'Public Order & Security', code: '03', approved: 6_400, revised: 6_500, actual: 6_100, color: BUDGET_COLORS.security },
      { id: 'economy', name: 'Afaceri Economice', nameRu: 'Экономические вопросы', nameEn: 'Economic Affairs', code: '04', approved: 5_500, revised: 5_600, actual: 5_200, color: BUDGET_COLORS.economy },
      { id: 'defense', name: 'Apărare Națională', nameRu: 'Национальная оборона', nameEn: 'National Defense', code: '02', approved: 2_700, revised: 2_700, actual: 2_500, color: BUDGET_COLORS.defense },
      { id: 'environment', name: 'Mediu și Resurse Naturale', nameRu: 'Охрана окружающей среды', nameEn: 'Environment', code: '05', approved: 2_200, revised: 2_200, actual: 2_000, color: BUDGET_COLORS.environment },
      { id: 'housing', name: 'Locuințe și Servicii Comunale', nameRu: 'Жилищно-коммунальные услуги', nameEn: 'Housing & Community', code: '06', approved: 1_300, revised: 1_300, actual: 1_200, color: BUDGET_COLORS.housing },
      { id: 'culture', name: 'Cultură, Sport și Recreere', nameRu: 'Культура, спорт и отдых', nameEn: 'Culture & Sport', code: '08', approved: 1_100, revised: 1_100, actual: 1_000, color: BUDGET_COLORS.culture },
      { id: 'debt', name: 'Datorie Publică', nameRu: 'Государственный долг', nameEn: 'Public Debt', code: '12', approved: 2_500, revised: 2_300, actual: 3_000, color: BUDGET_COLORS.debt },
    ],
  },
  2020: {
    year: 2020,
    totalApproved: 68_100,
    totalRevised: 69_000,
    totalActual: 65_200,
    executionRate: 94.5,
    sectors: [
      { id: 'social', name: 'Protecție Socială', nameRu: 'Социальная защита', nameEn: 'Social Protection', code: '10', approved: 19_100, revised: 19_500, actual: 18_500, color: BUDGET_COLORS.social },
      { id: 'education', name: 'Educație', nameRu: 'Образование', nameEn: 'Education', code: '09', approved: 12_200, revised: 12_400, actual: 11_600, color: BUDGET_COLORS.education },
      { id: 'health', name: 'Sănătate', nameRu: 'Здравоохранение', nameEn: 'Healthcare', code: '07', approved: 10_700, revised: 11_000, actual: 10_200, color: BUDGET_COLORS.health },
      { id: 'general', name: 'Servicii Generale de Stat', nameRu: 'Общегосударственные услуги', nameEn: 'General Public Services', code: '01', approved: 6_400, revised: 6_500, actual: 6_100, color: BUDGET_COLORS.general },
      { id: 'security', name: 'Ordine Publică și Securitate', nameRu: 'Общественный порядок', nameEn: 'Public Order & Security', code: '03', approved: 5_800, revised: 5_900, actual: 5_500, color: BUDGET_COLORS.security },
      { id: 'economy', name: 'Afaceri Economice', nameRu: 'Экономические вопросы', nameEn: 'Economic Affairs', code: '04', approved: 4_900, revised: 5_000, actual: 4_600, color: BUDGET_COLORS.economy },
      { id: 'defense', name: 'Apărare Națională', nameRu: 'Национальная оборона', nameEn: 'National Defense', code: '02', approved: 2_400, revised: 2_400, actual: 2_200, color: BUDGET_COLORS.defense },
      { id: 'environment', name: 'Mediu și Resurse Naturale', nameRu: 'Охрана окружающей среды', nameEn: 'Environment', code: '05', approved: 2_000, revised: 2_000, actual: 1_900, color: BUDGET_COLORS.environment },
      { id: 'housing', name: 'Locuințe și Servicii Comunale', nameRu: 'Жилищно-коммунальные услуги', nameEn: 'Housing & Community', code: '06', approved: 1_200, revised: 1_200, actual: 1_100, color: BUDGET_COLORS.housing },
      { id: 'culture', name: 'Cultură, Sport și Recreere', nameRu: 'Культура, спорт и отдых', nameEn: 'Culture & Sport', code: '08', approved: 900, revised: 900, actual: 800, color: BUDGET_COLORS.culture },
      { id: 'debt', name: 'Datorie Publică', nameRu: 'Государственный долг', nameEn: 'Public Debt', code: '12', approved: 2_500, revised: 2_200, actual: 2_700, color: BUDGET_COLORS.debt },
    ],
  },
  2019: {
    year: 2019,
    totalApproved: 62_300,
    totalRevised: 62_800,
    totalActual: 59_800,
    executionRate: 95.2,
    sectors: [
      { id: 'social', name: 'Protecție Socială', nameRu: 'Социальная защита', nameEn: 'Social Protection', code: '10', approved: 17_400, revised: 17_600, actual: 16_800, color: BUDGET_COLORS.social },
      { id: 'education', name: 'Educație', nameRu: 'Образование', nameEn: 'Education', code: '09', approved: 11_100, revised: 11_200, actual: 10_600, color: BUDGET_COLORS.education },
      { id: 'health', name: 'Sănătate', nameRu: 'Здравоохранение', nameEn: 'Healthcare', code: '07', approved: 9_800, revised: 9_900, actual: 9_400, color: BUDGET_COLORS.health },
      { id: 'general', name: 'Servicii Generale de Stat', nameRu: 'Общегосударственные услуги', nameEn: 'General Public Services', code: '01', approved: 5_900, revised: 5_900, actual: 5_600, color: BUDGET_COLORS.general },
      { id: 'security', name: 'Ordine Publică și Securitate', nameRu: 'Общественный порядок', nameEn: 'Public Order & Security', code: '03', approved: 5_300, revised: 5_300, actual: 5_000, color: BUDGET_COLORS.security },
      { id: 'economy', name: 'Afaceri Economice', nameRu: 'Экономические вопросы', nameEn: 'Economic Affairs', code: '04', approved: 4_500, revised: 4_600, actual: 4_300, color: BUDGET_COLORS.economy },
      { id: 'defense', name: 'Apărare Națională', nameRu: 'Национальная оборона', nameEn: 'National Defense', code: '02', approved: 2_200, revised: 2_200, actual: 2_000, color: BUDGET_COLORS.defense },
      { id: 'environment', name: 'Mediu și Resurse Naturale', nameRu: 'Охрана окружающей среды', nameEn: 'Environment', code: '05', approved: 1_800, revised: 1_800, actual: 1_700, color: BUDGET_COLORS.environment },
      { id: 'housing', name: 'Locuințe și Servicii Comunale', nameRu: 'Жилищно-коммунальные услуги', nameEn: 'Housing & Community', code: '06', approved: 1_100, revised: 1_100, actual: 1_000, color: BUDGET_COLORS.housing },
      { id: 'culture', name: 'Cultură, Sport și Recreere', nameRu: 'Культура, спорт и отдых', nameEn: 'Culture & Sport', code: '08', approved: 800, revised: 800, actual: 700, color: BUDGET_COLORS.culture },
      { id: 'debt', name: 'Datorie Publică', nameRu: 'Государственный долг', nameEn: 'Public Debt', code: '12', approved: 2_400, revised: 2_400, actual: 2_700, color: BUDGET_COLORS.debt },
    ],
  },
};

export const BUDGET_TREND: BudgetTrend[] = [
  { year: 2019, approved: 62.3, actual: 59.8, euFunds: 2.1 },
  { year: 2020, approved: 68.1, actual: 65.2, euFunds: 2.8 },
  { year: 2021, approved: 75.4, actual: 72.4, euFunds: 3.5 },
  { year: 2022, approved: 84.2, actual: 79.8, euFunds: 5.2 },
  { year: 2023, approved: 93.1, actual: 88.5, euFunds: 7.8 },
  { year: 2024, approved: 100.0, actual: 94.2, euFunds: 9.4 },
];

export const AVAILABLE_YEARS = [2024, 2023, 2022, 2021, 2020, 2019];

export function getBudgetData(year: number): BudgetYearData | null {
  return BUDGET_DATA[year] ?? null;
}

export function computeSectorPct(data: BudgetYearData): BudgetYearData {
  return {
    ...data,
    sectors: data.sectors.map((s) => ({
      ...s,
      pct: (s.approved / data.totalApproved) * 100,
    })),
  };
}
