import type { Tender, ProcurementStats } from './types';

export const PROCUREMENT_STATS: ProcurementStats = {
  year: 2024,
  totalProcedures: 87_432,
  totalVolumeMDL: 41_800_000_000,
  activeTenders: 3_241,
  awardedContracts: 71_890,
  cancelledTenders: 12_301,
  avgContractValue: 478_000,
  competitiveRate: 73.4,
};

export const PROCUREMENT_BY_SECTOR = [
  { sector: 'Sănătate', sectorEn: 'Healthcare', sectorRu: 'Здравоохранение', volume: 8_900, count: 14_200 },
  { sector: 'Infrastructură', sectorEn: 'Infrastructure', sectorRu: 'Инфраструктура', volume: 7_600, count: 3_400 },
  { sector: 'Educație', sectorEn: 'Education', sectorRu: 'Образование', volume: 5_200, count: 18_600 },
  { sector: 'IT & Digitalizare', sectorEn: 'IT & Digitization', sectorRu: 'ИТ и цифровизация', volume: 4_100, count: 6_800 },
  { sector: 'Apărare & Securitate', sectorEn: 'Defense & Security', sectorRu: 'Оборона и безопасность', volume: 3_800, count: 2_100 },
  { sector: 'Agricultură', sectorEn: 'Agriculture', sectorRu: 'Сельское хозяйство', volume: 2_900, count: 7_300 },
  { sector: 'Energie', sectorEn: 'Energy', sectorRu: 'Энергетика', volume: 2_400, count: 1_800 },
  { sector: 'Cultură & Sport', sectorEn: 'Culture & Sport', sectorRu: 'Культура и спорт', volume: 1_200, count: 4_600 },
  { sector: 'Altele', sectorEn: 'Other', sectorRu: 'Другие', volume: 5_700, count: 28_632 },
];

export const TENDERS: Tender[] = [
  {
    id: 'ocds-b3wdp1-MD-2024-001',
    ocid: 'ocds-b3wdp1-MD-2024-001',
    title: 'Achiziția echipamentelor medicale pentru IMSP Spitalul Clinic Republican',
    titleRu: 'Закупка медицинского оборудования для ПМСУ Республиканская клиническая больница',
    authority: 'Ministerul Sănătății',
    authorityId: 'MD-0001-MoH',
    sector: 'Sănătate',
    sectorRo: 'Sănătate',
    value: 45_800_000,
    currency: 'MDL',
    status: 'awarded',
    method: 'open',
    publishedDate: '2024-02-15',
    deadlineDate: '2024-03-20',
    winner: 'MedEquip SRL',
    bids: 4,
  },
  {
    id: 'ocds-b3wdp1-MD-2024-002',
    ocid: 'ocds-b3wdp1-MD-2024-002',
    title: 'Reabilitarea drumului național R3 Chișinău–Hîncești, tronsonul km 0–25',
    titleRu: 'Реабилитация национальной дороги R3 Кишинёв–Хынчешть, участок км 0–25',
    authority: 'Agenția Națională a Drumurilor',
    authorityId: 'MD-0002-AND',
    sector: 'Infrastructură',
    sectorRo: 'Infrastructură',
    value: 312_000_000,
    currency: 'MDL',
    status: 'awarded',
    method: 'open',
    publishedDate: '2024-01-08',
    deadlineDate: '2024-02-28',
    winner: 'Drumuri SA',
    bids: 3,
  },
  {
    id: 'ocds-b3wdp1-MD-2024-003',
    ocid: 'ocds-b3wdp1-MD-2024-003',
    title: 'Sisteme informatice integrate pentru Ministerul Finanțelor – Trezoreria de Stat',
    titleRu: 'Интегрированные информационные системы для Министерства финансов – Государственное казначейство',
    authority: 'Ministerul Finanțelor',
    authorityId: 'MD-0003-MoF',
    sector: 'IT & Digitalizare',
    sectorRo: 'IT & Digitalizare',
    value: 28_600_000,
    currency: 'MDL',
    status: 'active',
    method: 'open',
    publishedDate: '2024-03-10',
    deadlineDate: '2024-04-25',
    bids: 0,
  },
  {
    id: 'ocds-b3wdp1-MD-2024-004',
    ocid: 'ocds-b3wdp1-MD-2024-004',
    title: 'Livrarea manualelor școlare pentru ciclul primar, ediția 2024-2025',
    titleRu: 'Поставка школьных учебников для начальной школы, издание 2024-2025',
    authority: 'Ministerul Educației și Cercetării',
    authorityId: 'MD-0004-MoEC',
    sector: 'Educație',
    sectorRo: 'Educație',
    value: 14_200_000,
    currency: 'MDL',
    status: 'complete',
    method: 'open',
    publishedDate: '2024-01-20',
    deadlineDate: '2024-02-15',
    winner: 'Lumina Editorial SRL',
    bids: 5,
  },
  {
    id: 'ocds-b3wdp1-MD-2024-005',
    ocid: 'ocds-b3wdp1-MD-2024-005',
    title: 'Construcția rețelei de canalizare în raionul Ungheni, 12 localități',
    titleRu: 'Строительство канализационной сети в районе Унгень, 12 населённых пунктов',
    authority: 'Agenția pentru Dezvoltare Regională Centru',
    authorityId: 'MD-0005-ADRC',
    sector: 'Infrastructură',
    sectorRo: 'Infrastructură',
    value: 87_400_000,
    currency: 'MDL',
    status: 'awarded',
    method: 'open',
    publishedDate: '2024-02-01',
    deadlineDate: '2024-03-10',
    winner: 'ApaCanal SRL',
    bids: 2,
  },
  {
    id: 'ocds-b3wdp1-MD-2024-006',
    ocid: 'ocds-b3wdp1-MD-2024-006',
    title: 'Achiziția produselor alimentare pentru grădinițele municipale Chișinău',
    titleRu: 'Закупка продуктов питания для муниципальных детских садов Кишинёва',
    authority: 'Primăria Municipiului Chișinău',
    authorityId: 'MD-0006-PMC',
    sector: 'Educație',
    sectorRo: 'Educație',
    value: 9_800_000,
    currency: 'MDL',
    status: 'active',
    method: 'open',
    publishedDate: '2024-03-18',
    deadlineDate: '2024-04-15',
    bids: 0,
  },
  {
    id: 'ocds-b3wdp1-MD-2024-007',
    ocid: 'ocds-b3wdp1-MD-2024-007',
    title: 'Servicii de securitate a informației pentru autoritățile publice centrale',
    titleRu: 'Услуги информационной безопасности для центральных органов государственной власти',
    authority: 'Agenția de Guvernare Electronică',
    authorityId: 'MD-0007-AGE',
    sector: 'IT & Digitalizare',
    sectorRo: 'IT & Digitalizare',
    value: 6_400_000,
    currency: 'MDL',
    status: 'cancelled',
    method: 'limited',
    publishedDate: '2024-01-30',
    deadlineDate: '2024-02-28',
    bids: 1,
  },
  {
    id: 'ocds-b3wdp1-MD-2024-008',
    ocid: 'ocds-b3wdp1-MD-2024-008',
    title: 'Achiziția vaccinurilor pentru campania națională de imunizare 2024',
    titleRu: 'Закупка вакцин для национальной кампании иммунизации 2024 года',
    authority: 'Ministerul Sănătății',
    authorityId: 'MD-0001-MoH',
    sector: 'Sănătate',
    sectorRo: 'Sănătate',
    value: 31_200_000,
    currency: 'MDL',
    status: 'awarded',
    method: 'direct',
    publishedDate: '2024-02-20',
    deadlineDate: '2024-03-05',
    winner: 'PharmaCentral SA',
    bids: 1,
  },
  {
    id: 'ocds-b3wdp1-MD-2024-009',
    ocid: 'ocds-b3wdp1-MD-2024-009',
    title: 'Modernizarea sistemului de iluminat public în mun. Bălți',
    titleRu: 'Модернизация системы уличного освещения в мун. Бэлць',
    authority: 'Primăria Municipiului Bălți',
    authorityId: 'MD-0008-PMB',
    sector: 'Infrastructură',
    sectorRo: 'Infrastructură',
    value: 22_600_000,
    currency: 'MDL',
    status: 'awarded',
    method: 'open',
    publishedDate: '2024-01-15',
    deadlineDate: '2024-02-20',
    winner: 'ElectroLux SRL',
    bids: 6,
  },
  {
    id: 'ocds-b3wdp1-MD-2024-010',
    ocid: 'ocds-b3wdp1-MD-2024-010',
    title: 'Dotarea laboratoarelor din licee cu echipamente STEM',
    titleRu: 'Оснащение лабораторий лицеев оборудованием STEM',
    authority: 'Ministerul Educației și Cercetării',
    authorityId: 'MD-0004-MoEC',
    sector: 'Educație',
    sectorRo: 'Educație',
    value: 18_900_000,
    currency: 'MDL',
    status: 'active',
    method: 'open',
    publishedDate: '2024-03-22',
    deadlineDate: '2024-05-10',
    bids: 0,
  },
  {
    id: 'ocds-b3wdp1-MD-2024-011',
    ocid: 'ocds-b3wdp1-MD-2024-011',
    title: 'Servicii de consultanță pentru implementarea reformei bugetare conform standardelor UE',
    titleRu: 'Консультационные услуги по реализации бюджетной реформы в соответствии со стандартами ЕС',
    authority: 'Ministerul Finanțelor',
    authorityId: 'MD-0003-MoF',
    sector: 'IT & Digitalizare',
    sectorRo: 'Servicii',
    value: 4_100_000,
    currency: 'MDL',
    status: 'complete',
    method: 'limited',
    publishedDate: '2023-12-01',
    deadlineDate: '2023-12-20',
    winner: 'EuroCons SA',
    bids: 3,
  },
  {
    id: 'ocds-b3wdp1-MD-2024-012',
    ocid: 'ocds-b3wdp1-MD-2024-012',
    title: 'Reparația capitală a spitalului raional Orhei',
    titleRu: 'Капитальный ремонт районной больницы Орхей',
    authority: 'Consiliul Raional Orhei',
    authorityId: 'MD-0009-CRO',
    sector: 'Sănătate',
    sectorRo: 'Sănătate',
    value: 56_700_000,
    currency: 'MDL',
    status: 'awarded',
    method: 'open',
    publishedDate: '2024-01-25',
    deadlineDate: '2024-03-01',
    winner: 'ConstructMed SA',
    bids: 2,
  },
  {
    id: 'ocds-b3wdp1-MD-2024-013',
    ocid: 'ocds-b3wdp1-MD-2024-013',
    title: 'Achiziția de combustibil și lubrifianți pentru Ministerul Apărării',
    titleRu: 'Закупка топлива и смазочных материалов для Министерства обороны',
    authority: 'Ministerul Apărării',
    authorityId: 'MD-0010-MoD',
    sector: 'Apărare & Securitate',
    sectorRo: 'Apărare',
    value: 38_400_000,
    currency: 'MDL',
    status: 'awarded',
    method: 'limited',
    publishedDate: '2024-02-10',
    deadlineDate: '2024-02-25',
    winner: 'PetrolMD SRL',
    bids: 2,
  },
  {
    id: 'ocds-b3wdp1-MD-2024-014',
    ocid: 'ocds-b3wdp1-MD-2024-014',
    title: 'Sistem de monitorizare video a traficului rutier în Chișinău',
    titleRu: 'Система видеомониторинга дорожного движения в Кишинёве',
    authority: 'Primăria Municipiului Chișinău',
    authorityId: 'MD-0006-PMC',
    sector: 'IT & Digitalizare',
    sectorRo: 'IT & Digitalizare',
    value: 16_200_000,
    currency: 'MDL',
    status: 'active',
    method: 'open',
    publishedDate: '2024-03-28',
    deadlineDate: '2024-05-15',
    bids: 0,
  },
  {
    id: 'ocds-b3wdp1-MD-2024-015',
    ocid: 'ocds-b3wdp1-MD-2024-015',
    title: 'Reabilitarea sistemului de irigare în raionul Cahul – 4.800 ha',
    titleRu: 'Реабилитация ирригационной системы в районе Кахул – 4.800 га',
    authority: 'Agenția Națională pentru Siguranța Alimentelor',
    authorityId: 'MD-0011-ANSA',
    sector: 'Agricultură',
    sectorRo: 'Agricultură',
    value: 124_000_000,
    currency: 'MDL',
    status: 'awarded',
    method: 'open',
    publishedDate: '2024-01-05',
    deadlineDate: '2024-02-20',
    winner: 'AgroIrigare SRL',
    bids: 3,
  },
];

export function searchTenders(query: string, sector?: string, status?: string): Tender[] {
  return TENDERS.filter((t) => {
    const matchesQuery =
      !query ||
      t.title.toLowerCase().includes(query.toLowerCase()) ||
      t.authority.toLowerCase().includes(query.toLowerCase()) ||
      t.ocid.toLowerCase().includes(query.toLowerCase());
    const matchesSector = !sector || sector === 'all' || t.sector === sector;
    const matchesStatus = !status || status === 'all' || t.status === status;
    return matchesQuery && matchesSector && matchesStatus;
  });
}

export const PROCUREMENT_SECTORS = [
  'Sănătate',
  'Infrastructură',
  'Educație',
  'IT & Digitalizare',
  'Apărare & Securitate',
  'Agricultură',
  'Energie',
  'Cultură & Sport',
];
